version: '3'

services:
    PostgreSQL:
      restart: always
      image: postgres:alpine
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=pass
        - POSTGRES_DB=db
